name: Codeforces Sync
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Codeforces Sync Action
        uses: DhyeyThumar/codeforces-sync-action@v1.0.1
        with:
          cf_handle: ${{ secrets.CF_HANDLE }}
          gh_token: ${{ secrets.GH_TOKEN }}
