name: Codeforces Sync
on:
  schedule:
    - cron: '0 */6 * * *' # প্রতি ৬ ঘণ্টা পর পর আপডেট হবে
  workflow_dispatch: # ম্যানুয়ালি রান করার জন্য

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Codeforces Sync
        uses: itmo-solutions/codeforces-sync@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          handle: ${{ secrets.CF_HANDLE }}
