name: Codeforces Sync
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: itmo-solutions/codeforces-sync@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          handle: ${{ secrets.CF_HANDLE }}
